name: BigBrother
main: shoghicp\BigBrother\BigBrother
load: STARTUP
author: BigBrotherTeam
version: 2.0.0
api: 5.0.0
description: "Allows the connection of Minecraft: PC clients to PocketMine-MP servers"
website: https://github.com/BigBrotherTeam/BigBrother
